env:
    DEVICE_CODENAME: rosy
    BUILD_USER: rosy
    BUILD_HOST: nhAsif
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "ENCRYPTED[!531d379b60bce5f5166acc4f1581edd569cf260d601f65d93a8d373bb704a089f7c9b1c7f6c27c72b8eeb061abcc108f!]"
    TG_TOKEN: "ENCRYPTED[!d855ccfb93d92774f3ab00c869442874951880ab299ab5f70099962e2f651832bd253a8139081ac30bb3a2cc69770c27!]"
    TG_CHAT_ID: "ENCRYPTED[!e810ad5bf528a3a2226620df6e6daa5064783525bf592963e647e2d045423b31537c70027a8085718d089898544fd241!]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Environment_script:
      - cat /etc/os*
      - env

  Spec-Check_script:
      - ./disk.sh
  
  Sync_script:
      - ./download.sh

  Build_clang_gcc_script:
      - ./clang.sh
      
  Notif_script:
      - ./done.sh
 
  Build_gcc_script:
      - ./gcc.sh

  Notif_script:
      - ./done.sh
