env:
    DEVICE_CODENAME: ulysse 
    BUILD_USER: leeroy
    BUILD_HOST: jenkinsn
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "ENCRYPTED[!531d379b60bce5f5166acc4f1581edd569cf260d601f65d93a8d373bb704a089f7c9b1c7f6c27c72b8eeb061abcc108f!]"
    TG_TOKEN: "ENCRYPTED[!798e786ae296cc6a8e4c6791b7727314d504a1af31b0b6a050128b7efba795d21bf4266ef82bdbcecae4266060a2e503!]"
    TG_CHAT_ID: "ENCRYPTED[!2a637243e1a379e4696e0579f78cc5505635a61d08ff9389a0d451c29282e163baf8dfa3eee95acbf2e7c21a166baaa3!]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Environment_script:
      - cat /etc/os*
      - env

  Spec-Check_script:
      - ./disk.sh
  
  Sync_script:
      - ./download.sh

  Build_clang_script:
      - ./clang.sh

  Notif_script_gcc:
      - ./done.sh
      
  Build_gcc_script:
      - ./gcc.sh

  Notif_script_gcc:
      - ./done.sh
